name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch: 
          - 386 
          - amd64
          - arm64
        exclude:  
          - arch: "386"
            os: darwin 

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install nim
        uses: iffy/install-nim@v4.1.3
      - name: Build
        run: |
          nimble install -d -y
          nim c -d:release src/dye.nim
      - uses: actions/upload-artifact@v2
        with:
          name: dye-${{ matrix.os }}-${{ matrix.arch }}
          path: src/dye
