name: Build

on:
  workflow_dispatch: 
  release: 
    types: [released]

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [386, amd64, arm64]
        exclude:  
          - arch: "386"
            os: darwin 
          - arch: arm64
            os: windows 

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install nim
        uses: iffy/install-nim@v4.1.3
      - name: Build
        run: |
          nimble install -d -y
          nim c -d:release src/dye.nim
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os != 'windows' }}
        with:
          name: dye-${{ matrix.os }}-${{ matrix.arch }}
          path: src/dye
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows' }}
        with:
          name: dye-${{ matrix.os }}-${{ matrix.arch }}
          path: src/dye
      - name: Release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["dye-*-*"]'

          
  
