name: Build

on:
  workflow_dispatch: 
  release: 
    types: [released]

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch: 
          - 386 
          - amd64
          - arm64
        exclude:  
          - arch: "386"
            os: darwin 

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install nim
        uses: iffy/install-nim@v4.1.3
      - name: Build
        run: |
          nimble install -d -y
          nimble build
          mkdir dye-bin
          cp dye dye-bin
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dye-${{ matrix.os }}-${{ matrix.arch }}.zip dye/dye
      - name: Release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["dye-*-*.zip"]'
